version: '3.9'
services:
  mongo:
    image: mongo:7
    restart: always
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    environment:
      - MONGO_URL=mongodb://mongo:27017/codex-todo
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://backend:3000/api
    ports:
      - "5173:4173"
    depends_on:
      - backend

volumes:
  mongo-data:
